# Anima LoRA Training Configuration Template
# Model paths are loaded from Global Settings automatically.

[training_arguments]
output_name = "my_anima_lora"
save_model_as = "safetensors"
max_train_steps = 12000
save_every_n_steps = 250
save_last_n_steps_state = 2
log_with = "tensorboard"
learning_rate = 2e-5
text_encoder_lr = 0.0
optimizer_type = "AdamW"
optimizer_args = [ "weight_decay=0.01",]
lr_scheduler = "constant"
lr_warmup_steps = 100
mixed_precision = "bf16"
gradient_checkpointing = true
gradient_accumulation_steps = 1
flash_attn = false
torch_compile = false
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
seed = 42
cache_latents_to_disk = true
cache_text_encoder_outputs_to_disk = true
skip_cache_check = false
sample_every_n_steps = 250
freeze_llm_adapter = true
freeze_inserted_only_training = false

# Muon Defaults
use_muon = false
muon_lr = 0.02
muon_lr_scale = 0.05
muon_momentum = 0.95
muon_weight_decay = 0.01
muon_ns_steps = 5
muon_adam_betas = "0.9,0.95"
muon_adam_eps = "1e-8"
muon_param_filter = "self_attn_mlp_cross"
muon_disable_for_llm_adapter = true
muon_disable_for_adaln = true
muon_disable_distributed_allgather = false
muon_fp32_sensitive = false


[network_arguments]
network_module = "networks.lora_anima38"
network_dim = 32
network_alpha = 32
network_train_unet_only = true

[anima38_arguments]
timestep_sampling = "sigmoid"
discrete_flow_shift = 3.0
weighting_scheme = "none"
