[general]
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 256
max_bucket_reso = 1536
bucket_reso_steps = 16

[[datasets]]
resolution = [1536, 1536]
batch_size = 2
caption_extension = ".txt"

  [[datasets.subsets]]
  image_dir = ""
  num_repeats = 1
  keep_tokens = 1
  flip_aug = false
  caption_prefix = ""
  shuffle_caption = false
  caption_tag_dropout_rate = 0.0
  caption_dropout_rate = 0.05
  caption_dropout_every_n_epochs = 0
