venv_path = ""

[model_paths]
# Anima 3.8B Paths
anima38_dit_path = ""
anima38_qwen3_path = ""
anima38_qwen35_path = ""
anima38_vae_path = ""

# Anima Paths
dit_path = ""
qwen3_path = ""
vae_path = ""

# Lumina Paths
lumina_dit_path = ""
gemma2_path = ""
lumina_vae_path = ""

[ui]
background = ""
background_position = "50% 50%"
dim_level = 0
brightness_level = 100
blur_level = 0
text_shadow_size = 0
theme = "github-dark"

